#!/usr/bin/env bash

MONO=$(which mono)
BOOGIE=$(dirname "${BASH_SOURCE[0]}")/Boogie.exe

if [[ ! -x "$MONO" ]]; then
    echo "Error: Dafny requires Mono to run on non-Windows systems."
    exit 1
fi

if [[ ! -x "$BOOGIE" ]]; then
    echo "Error: Boogie.exe not found at $BOOGIE."
    exit 1
fi

"$MONO" "$BOOGIE" "$@"
